### ISSUE TITLE
qga timeout 

### ISSUE THREAD

**Issue by crab2313** [danobi/vmtest#17]
Without the following patch, vmtest simply failed to execute guest-sync on qga socket (on my box).

```
diff --git a/src/qga.rs b/src/qga.rs
index 445d11d..55b056b 100644
--- a/src/qga.rs
+++ b/src/qga.rs
@@ -72,6 +72,9 @@ impl QgaWrapper {
         recv_req: Receiver<QgaWrapperCommand>,
         send_resp: Sender<Result<QgaWrapperCommandResp>>,
     ) {
+
+        std::thread::sleep(std::time::Duration::from_millis(1000 * 20));
+
```

**Comment by crab2313** [comment]
Failed to connect QGA

Caused by:
    Timed out waiting for QGA

**Comment by crab2313** [comment]
QEMU 8.0.2 on latest archlinux with a qemu-guest-agent 6.2.1

**Comment by crab2313** [comment]
It seems that QGA socket will not response anything in OVMF and grub state. And that make the first send of guest-sync block forever hence a timeout.

**Comment by danobi** [comment]
Ah, perhaps a retry in the qga init code is necessary. As you've probably seen, I went through some effort in `qga.rs` to make sure operations could be properly timed out.

**Comment by DolceTriade** [comment]
I'm seeing this as well, and the issue is exactly a retry loop is required. If you connect to the QGA socket *immediately* after it is created, it will never respond to any commands you send it until you recreate the socket. Adding a sleep "fixes" it. We should probably do the same we do in connect_to_qmp socket, except the architecture of the QGA socket makes it a little messy since the actual requests and responses are handled on a separate thread.
