### ISSUE TITLE
drop into an interactive shell

### ISSUE THREAD

**Issue by chantra** [danobi/vmtest#54]
I had that use case in mind, and so did @liu-song-6, so bringing this up here.

ATM we can only run one-off commands and see the outcome. At times, when further investigation needs to be done, it can be useful to drop in a shell.

The work around I have found currently is to:
- RUST_LOG=debug vmtest -k kernel ls
- intterupt the run so it leave the init file on disk
- copy the qemu command from the debug logs
- edit the init script, change to run qemu-ga in the background and add `bash` on the next line.
- paste the qemu command.

Making this more practical/usable can be useful though.

Any thoughts? What would be a good way to implement this? maybe through serial?

**Comment by danobi** [comment]
Hmm, I wonder if it's possible to selectively wire up stdin from terminal to qemu. I believe that's how virtme works -- it transfers guest control to bash. I think it'd be fine if it's not too intrusive on the codebase. The goal of `vmtest` is test infra -- I kinda see an interactive shell as more of a debugging tool rather than a testing tool.

**Comment by chantra** [comment]
> Hmm, I wonder if it's possible to selectively wire up stdin from terminal to qemu. I believe that's how virtme works -- it transfers guest control to bash. I think it'd be fine if it's not too intrusive on the codebase. The goal of `vmtest` is test infra -- I kinda see an interactive shell as more of a debugging tool rather than a testing tool.

Hopefully #58 is smooth enough of an approach :)
