### ISSUE TITLE
Faster feedback for totally broken kernels

### ISSUE THREAD

**Issue by bjackman** [danobi/vmtest#99]
My specific case is that I have a configuration that fails totally to boot. IIUC from a quick look at `qemu.rs` I think the behaviuor I'm seeing is expected, but it's a bit suboptimal: the guest fails to boot, and then `vmtest` waits for 60s before failing and showing me the full console log.

Before looking at the code I thought I could just set `init=-1` on the kernel cmdline and `--no-reboot` in the QEMU args. That means as soon as the guest kernel panics, QEMU exits. But there's nothing in place to detect that exit AFAICS.

My first thought is to start by having the QGA bringup be interrupted if the child QEMU process exits - this would still require the user to manually set `--no-reboot`, but maybe that's fine? And maybe even necessary so that people can actually test system rests in `vmtest`? What do you think?

**Comment by bjackman** [comment]
Oh also note: the best workaround I found is to look in `.vmtest.log`. In there is a big QEMU command you can copy-paste (you need to fiddle a bit to get rid of references to temp files that don't exist) to do further investigations on the broken kernel.

**Comment by danobi** [comment]
Agreed, would be great to have a better way to bail if kernel is borked. 

Btw, you mean `panic=-1` and not `init=-1`, right? If so, we already set this: https://github.com/danobi/vmtest/blob/80cd7b5127fe1d9e591bfc29f52075574add0afc/src/qemu.rs#L374-L375
https://github.com/danobi/vmtest/blob/80cd7b5127fe1d9e591bfc29f52075574add0afc/src/qemu.rs#L409-L411

I'm guessing the code is polling on qga socket without looking at qemu process. Maybe it should also look at qemu process status. Been a while since I've looked at that code. Lemme put it on my todo list.

**Comment by bjackman** [comment]
> Btw, you mean panic=-1 and not init=-1, right?

Oops, yes I do.

> If so, we already set this: 

Ah - nice, then I guess all that's missing here is the plumbing to notice the child dying, and my concerns about hard-coding the behaviour were not necessary :)
